// src/pages/Destination.jsx
import React from 'react'

function Destination() {
  return (
    <main className="min-h-screen md:min-h-unset md:h-screen flex flex-col space-y-5 justify-center items-center md:items-end  text-center md:text-left md:flex-row md:px-[10%] bg-no-repeat bg-center bg-cover bg-[url('./assets/destination/background-destination-mobile.jpg')] sm:bg-[url('./assets/destination/background-destination-tablet.jpg')] lg:bg-[url('./assets/destination/background-destination-desktop.jpg')]">
      
      
    </main>
  )
}

export default Destination

// src/components/destination/Destination.vue
<template>
  <main class="h-screen text-white bg-[url('/src/assets/destination/background-destination-mobile.jpg')] md:bg-[url('/src/assets/destination/background-destination-tablet.jpg')] lg:bg-[url('/src/assets/destination/background-destination-desktop.jpg')] bg-no-repeat bg-cover">
      <destination-navbar></destination-navbar>
      <router-view></router-view>
  </main>
</template>

<script>
import DestinationNavbar from './destinationNavbar.vue'
export default {
  name: 'app',
  data () {
    return {
    }
  },
  components: {
    'destination-navbar': DestinationNavbar,
  }
}
</script>
